# https://github.com/lowlighter/metrics#-documentation
name: Metrics
on:
    schedule: [{ cron: "0 1 * * *" }]
    workflow_dispatch:
    push: { branches: ["main"] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        environment:
            name: production
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  token: ${{ secrets.METRICS_TOKEN }}
                  user: SiebeBaree
                  template: classic
                  base: header, activity, community, repositories, metadata
                  base_hireable: yes
                  config_timezone: Europe/Brussels
                  plugin_achievements: yes
                  plugin_achievements_display: detailed
                  plugin_achievements_secrets: yes
                  plugin_achievements_threshold: C
                  plugin_habits: yes
                  plugin_habits_charts_type: classic
                  plugin_habits_days: 30
                  plugin_habits_facts: yes
                  plugin_habits_from: 200
                  plugin_habits_languages_limit: 5
                  plugin_habits_languages_threshold: 5%
                  plugin_languages: yes
                  plugin_languages_analysis_timeout: 15
                  plugin_languages_analysis_timeout_repositories: 7.5
                  plugin_languages_categories: markup, programming
                  plugin_languages_colors: github
                  plugin_languages_limit: 5
                  plugin_languages_recent_categories: markup, programming
                  plugin_languages_recent_days: 14
                  plugin_languages_recent_load: 300
                  plugin_languages_sections: most-used
                  plugin_languages_threshold: 5%
                  plugin_lines: yes
                  plugin_lines_history_limit: 25
                  plugin_lines_repositories_limit: 100
                  plugin_lines_sections: base
