# https://github.com/lowlighter/metrics#-documentation
name: Metrics
on:
    schedule: [{ cron: "0 1 * * *" }]
    workflow_dispatch:
    push: { branches: ["main"] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        environment:
            name: production
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  token: ${{ secrets.METRICS_TOKEN }}
                  user: SiebeBaree
                  template: classic
                  base: header, activity, community, repositories, metadata
                  base_hireable: yes
                  config_timezone: Europe/Brussels
                  plugin_achievements: yes
                  plugin_achievements_display: compact
                  plugin_achievements_secrets: yes
                  plugin_achievements_threshold: X
                  plugin_habits: yes
                  plugin_habits_charts_type: classic
                  plugin_habits_days: 30
                  plugin_habits_facts: yes
                  plugin_habits_from: 200
                  plugin_habits_languages_limit: 8
                  plugin_habits_languages_threshold: 0%
                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: half-year
                  plugin_lines: yes
                  plugin_lines_history_limit: 25
                  plugin_lines_repositories_limit: 25
                  plugin_lines_sections: base
                  plugin_traffic: yes
